public class Exception
{
    public let message: string;
    public let inner_exception: Exception?;

    public init(.message = "") { }
    public init(.message, .inner_exception) { }
}
