public class Exception
{
    public let message: string;
    public let inner_exception: Exception?;

    public new(.message = "") { }
    public new(.message, .inner_exception) { }
}
